# Generated by Django 5.2.12 on 2026-04-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
    ]
