# Generated by Django 5.2.12 on 2026-04-18 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_offer_offers_is_dele_71e141_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='offer',
            name='offers_created_9f8ec4_idx',
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['-created_at'], name='offers_created_85053d_idx'),
        ),
    ]
