# Generated by Django 5.2.12 on 2026-04-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
